Create FAQ.md
jserranohidalgo/spark-intro pull request #1
Opened 2020-02-24 19:11 UTC by PumPumDev

2020-02-25 09:55 UTC, jserranohidalgo requested changes
Great start!
Thanks!

2020-02-25 09:55 UTC, jserranohidalgo commented on FAQ.md
> +A: You just have to download the latest .exe.After the instalation, when you turn it on it runs a Virtual Machine which use "normal" docker.
Minor typos: 

- "... the latest `.exe`. After ... ", quote `exe`, and add whitespace. 
- "which uses"

2020-02-25 19:26 UTC, PumPumDev commented
I've just changed the file

2020-02-26 08:34 UTC, jserranohidalgo commented
@alfonsorr @nmartinezs2017 @correosoria @yh89 Any additional question?

2020-04-07 19:21 UTC, merged